# Generated by Django 5.2.3 on 2025-08-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('is_showed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('music_name', models.CharField(max_length=100)),
                ('artist_name', models.CharField(max_length=100)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='img/songs/')),
                ('audio_file', models.FileField(upload_to='audio/')),
                ('is_fav', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='none', upload_to='img/playlists/')),
                ('description', models.CharField(default='none', max_length=150)),
                ('songs', models.ManyToManyField(related_name='playlists', to='main_page.song')),
            ],
        ),
    ]
