# Generated by Django 5.2.3 on 2025-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image',
            field=models.ImageField(default='', upload_to='img/playlists/'),
        ),
    ]
