# Generated by Django 5.2.3 on 2025-08-07 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_alter_playlist_description_alter_playlist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='main_page.song'),
        ),
    ]
